"""corret id to contact table in int 

Revision ID: 52634f5af1c3
Revises: 94065e5244ac
Create Date: 2025-10-21 17:22:21.432679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52634f5af1c3'
down_revision: Union[str, Sequence[str], None] = '94065e5244ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('contact', 'id',
#                existing_type=sa.CHAR(length=32),
#                type_=sa.Integer(),
#                existing_nullable=False)
#     op.alter_column('contactlistlink', 'contact_id',
#                existing_type=sa.CHAR(length=32),
#                type_=sa.Integer(),
#                existing_nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('contactlistlink', 'contact_id',
#                existing_type=sa.Integer(),
#                type_=sa.CHAR(length=32),
#                existing_nullable=False)
#     op.alter_column('contact', 'id',
#                existing_type=sa.Integer(),
#                type_=sa.CHAR(length=32),
#                existing_nullable=False)
#     # ### end Alembic commands ###

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
