"""update db

Revision ID: 9609391740b2
Revises: eda11fd9fb67
Create Date: 2025-10-21 14:09:15.875272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9609391740b2'
down_revision: Union[str, Sequence[str], None] = 'eda11fd9fb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# """ def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_index(op.f('ix_listcontact_list_name'), 'listcontact', ['list_name'], unique=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_listcontact_list_name'), table_name='listcontact')
#     # ### end Alembic commands ###
#  """


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
