"""add column  favorite and blocked

Revision ID: eda11fd9fb67
Revises: 4c6f6132d792
Create Date: 2025-10-20 16:04:47.498451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda11fd9fb67'
down_revision: Union[str, Sequence[str], None] = '4c6f6132d792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
